title: Das Digital Digest
description: M365-AzureDataEngineering.
theme: just-the-docs
search_enabled: true

#url: https://just-the-docs.github.io

aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Set a path/url to a logo that will be displayed instead of the title
#logo: "assests/images/digital_digest_icon.png"

# Set a path/url to a favicon that will be displayed by the browser
#favicon_ico: "assests/images/MySignature.png"


# Back to top link
back_to_top: true
back_to_top_text: "Back to top"